version: "3"
services:
  url-shortening-app:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/app
  redis-server:
    image: redis
